---
title: Maspeth Bible Church
timezone: UTC
collections:
  events:
    title: Events
    output: false
    starts_at: ''
    description: ''
  people:
    title: People
    output: true
  posts:
    title: Posts
    output: true
    key: default key
  uploads:
    title: Uploads
    output: true
email: tylergaugler16@gmail.com
description: We are a small church in Maspeth that seek to honor God in all we do.
  We think that the bible has given specific commands to each individual. Above all
  we are to love the Lord our God. Secondly, we are to love our neighbor.
baseurl: ''
url: maspethbiblechurch.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
plugins:
<<<<<<< HEAD
  - jekyll-feed

collections:
  - events

  scope:
      path: ""
      type: "events"
    values:
      description: ""
      stats_at: ""


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
=======
- jekyll-feed
>>>>>>> 6540643426f53b6c2099b8dce55f175730f34701
