---
title: Maspeth Bible Church
timezone: UTC
collections:
  events:
    title: Events
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: tylergaugler16@gmail.com
description: We are a small church in Maspeth that seek to honor God in all we do.
  We think that the bible has given specific commands to each individual. Above all
  we are to love the Lord our God. Secondly, we are to love our neighbor.
baseurl: ''
url: maspethbiblechurch.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
